version: '3.7'

services:     
  mariadb:
    container_name: web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: myWebCalculatorDb_6
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "5026:3306"
      
  web:
    container_name: 6_calculator
    hostname: app
    build: 6_Calculator/
    ports:
      - "0.0.0.0:5006:5006"
